### ISSUE TITLE
List navigation not working properly in Firefox

### ISSUE THREAD

**Issue by tomjnsn** [redlab/bootstrap-ext#3]
In your example using the arrow up and down keys works as it does on the bootstrap for WebKit browsers and IE (10 at least). However in Firefox 17.0.1 both on Mac and Windows it seems to ignore the arrow up and down keys even though the bootstrap typeahead still works on it.

**Comment by redlab** [comment]
Confirmed, arrow keys do not work on FF17.1 in Windows.

**Comment by redlab** [comment]
Action to take: merge in the updated code from updated typeahead

**Comment by redlab** [comment]
Fixed

**Comment by tomjnsn** [comment]
Thanks!

**Comment by redlab** [comment]
No problem, I have only tested it on Ubuntu, no Windows or Mac VM's hanging around at the moment. But it didn't work in FF on Ubuntu either.

**Comment by tomjnsn** [comment]
I've tested on both OS X and Windows in Firefox and can confirm it is
functioning properly now.
