### ISSUE TITLE
More data not appearing

### ISSUE THREAD

**Issue by lbcdigital** [redlab/bootstrap-ext#7]
The extra data that appears in the right hand well has stopped appearing incl on your demo. Any idea why and how to fix? Thanks!

**Comment by redlab** [comment]
I can't reproduce your problem, at least not in FireFox 
![example](https://cloud.githubusercontent.com/assets/1025047/11655755/8ede9c84-9db0-11e5-823d-341b9ade03ad.png)

Care to give some more information?

**Comment by lbcdigital** [comment]
Sorry I hadn't realised not all the countries had a description. I should read it better ;-) Thanks.
